com.nita/Controllers/ProvidersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using com.nita.IdentityModels;
using com.nita.Settings;
using com.nita.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Options;
using Nita.ViewModels.ProviderViewModels;

namespace Nita.Controllers
{
    [Authorize]
    public class ProvidersController : Controller
    {
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly IOptions<AppSettings> appSettings;
        private readonly IServiceProvider provider;
        private readonly IHostingEnvironment hostingEnvironment;

        public UserManager<ApplicationUser> UserManager => _userManager;

        public ProvidersController(
           IServiceProvider prov,
           IHostingEnvironment env,
           IOptions<AppSettings> appSettings, UserManager<ApplicationUser> userManager)
        {
            this.provider = prov;
            this.appSettings = appSettings;
            this.hostingEnvironment = env;
            this._userManager = userManager;
        }

        // GET: Providers
        public ActionResult Index(string countyId = "")
        {
            int passed;
            if (countyId!="" && countyId!="all") {
                 passed = Convert.ToInt32(countyId);
            }
            else {
                passed = 0;
            }
            var db = provider.GetRequiredService<ApplicationDbContext>();
            

            var counties = db.Counties.ToList();
            ViewBag.Counties = counties;
            if (passed == 0)
            {
                var trainingProviders = db.Trainers.Where(t=>t.Type == TrainerType.Institution).ToList();
                ViewBag.Trainers = trainingProviders;
                return View();
            }
            else if (passed != 0)
            {
                List<TrainerProfile> listProviders = new List<TrainerProfile>();
                
                var trainingProviders = db
                .Addresses
                .OrderBy(e => e.Id)
                .Where(a => a.CountyId == passed)
                .Join(db.Trainers.Where(t => t.Type == TrainerType.Institution),
                    addresses => addresses.Id,
                    trainers => trainers.AddressId,
                    (trainer, addresses) =>
                        new { addresses })
                .ToList();
                foreach (var trainer in trainingProviders)
                {
                    listProviders.Add(trainer.addresses);
                }
                ViewBag.Trainers = listProviders;
                return View();
            }
            else if (passed != 0)
            {
                List<TrainerProfile> listProviders = new List<TrainerProfile>();
                var trainingProviders = db
                .Addresses
                .OrderBy(e => e.Id)
                .Where(a => a.CountyId == passed)
                .Join(db.Trainers,
                    addresses => addresses.Id,
                    trainers => trainers.AddressId,
                    (trainer, addresses) =>
                        new { addresses })
                .ToList();
                foreach (var trainer in trainingProviders) {
                    listProviders.Add(trainer.addresses);
                }
                ViewBag.Trainers = listProviders;
                return View();
            }
            else {
                var trainingProviders = db.Trainers.Where(trainer => trainer.Type == TrainerType.Institution).ToList();
                ViewBag.Trainers = trainingProviders;
                return View();
            }
        }

        public ActionResult IndexMc(string countyId = "") {
            int passed;
            if (countyId != "" && countyId != "all")
            {
                passed = Convert.ToInt32(countyId);
            }
            else
            {
                passed = 0;
            }
            var db = provider.GetRequiredService<ApplicationDbContext>();

            var counties = db.Counties.ToList();
            ViewBag.Counties = counties;
            if (passed == 0)
            {
                var trainingProviders = db.Trainers.Where(t=>t.Type == TrainerType.MasterCraftman).ToList();
                ViewBag.Trainers = trainingProviders;
                return View();
            }
            else if (passed != 0)
            {
                List<TrainerProfile> listProviders = new List<TrainerProfile>();
               
                var trainingProviders = db
                .Addresses
                .OrderBy(e => e.Id)
                .Where(a => a.CountyId == passed)
                .Join(db.Trainers.Where(t => t.Type == TrainerType.MasterCraftman),
                    addresses => addresses.Id,
                    trainers => trainers.AddressId,
                    (trainer, addresses) =>
                        new { addresses })
                .ToList();
                foreach (var trainer in trainingProviders)
                {
                    listProviders.Add(trainer.addresses);
                }
                ViewBag.Trainers = listProviders;
                return View();
            }
            else if (passed != 0)
            {
                List<TrainerProfile> listProviders = new List<TrainerProfile>();
                var trainingProviders = db
                .Addresses
                .OrderBy(e => e.Id)
                .Where(a => a.CountyId == passed)
                .Join(db.Trainers,
                    addresses => addresses.Id,
                    trainers => trainers.AddressId,
                    (trainer, addresses) =>
                        new { addresses })
                .ToList();
                foreach (var trainer in trainingProviders)
                {
                    listProviders.Add(trainer.addresses);
                }
                ViewBag.Trainers = listProviders;
                return View();
            }
            else
            {
                var trainingProviders = db.Trainers.Where(trainer => trainer.Type == TrainerType.MasterCraftman).ToList();
                ViewBag.Trainers = trainingProviders;
                return View();
            }
        }

        // GET: Providers/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Providers/Create
        public ActionResult Create()
        {
            var db = provider.GetRequiredService<ApplicationDbContext>();
            var counties = db.Counties.ToList();
            var banks = db.PBanks.ToList();
            ViewBag.Banks = banks;
            ViewBag.Counties = counties;
            return View();
        }

        // GET: Providers/Create
        public ActionResult CreateMc()
        {
            var db = provider.GetRequiredService<ApplicationDbContext>();
            var counties = db.Counties.ToList();
            var banks = db.PBanks.ToList();
            ViewBag.Banks = banks;
            ViewBag.Counties = counties;
            return View();
        }

        public JsonResult GetBranches(int id)
        {
            var db = provider.GetRequiredService<ApplicationDbContext>();
            var branches = db.BankBranch.ToList();
            return Json(new { list = branches });
        }

        // POST: Providers/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> CreateAsync(ProviderModels model)
        {
            int TpId = 0;
            try
            {
                var db = provider.GetRequiredService<ApplicationDbContext>();
                var fullName = model.FullName.ToString();
                var contactPersonName = model.ContactPersonName.ToString();
                var contactPersonPosition = model.ContactPersonPosition.ToString();
                var roadStreet = model.StreetRoad.ToString();
                var buildingName = model.BuildingName.ToString();
                var contactEmail = model.ContactEmail.ToString();
                var landMark = model.LandMark.ToString();
                var countyId = model.CountyId.ToString();
                var trainerType = model.TrainerType.ToString();
                var telephoneNumber = model.Telephone.ToString();
                var postalAddress = model.PostalAddress.ToString();
                AccountType type = AccountType.Institution;
                TrainerType tType = TrainerType.Institution;
                if (trainerType == "Institution") {
                    type = AccountType.Institution;
                    tType = TrainerType.Institution;
                }
                else {
                    type = AccountType.MasterCraftsMan;
                    tType = TrainerType.MasterCraftman;
                }
                
                var user = new ApplicationUser()
                {
                    UserName = contactEmail,
                    Email = contactEmail,
                    PhoneNumber = telephoneNumber,
                    AccountType = type
                };

                //Create USer Account
                var result = await UserManager.CreateAsync(user, "123456789nita");
                if (result.Succeeded) {
                    //address
                    var address = new UserAddress();
                    address.BuildingName = buildingName;
                    address.CountyId = Convert.ToInt32(countyId);
                    address.NearbyLandmark = landMark;
                    address.Street = roadStreet;
                    address.Nationality = "Kenyan";
                    address.PAddress = postalAddress;
                    address.WTel = telephoneNumber;
                    //Add

com.nita/Views/Providers/Create-orig.cshtml
@using System.Collections.Generic
@using Microsoft.AspNetCore.Http
@using Microsoft.AspNetCore.Identity;
@model ProviderModels;
@{
    ViewData["Title"] = "Add a Training provider";
}
<link rel="icon" type="image/png" sizes="16x16" href="~/lib/images/favicon.png">
<!-- Bootstrap Core CSS -->
<link href="~/lib/plugins/bootstrap/css/bootstrap.min.css" rel="stylesheet">
<!-- Custom CSS -->
<link href="css/style.css" rel="stylesheet">
<!-- You can change the theme colors from here -->
<link href="css/colors/default-dark.css" id="theme" rel="stylesheet">

<div class="col-lg-12">
    <div class="card">
        <div class="card-body">
            <h4 class="card-title">Enter the training provider details</h4>
            <h6 class="card-subtitle">TP registration</h6>
            <form asp-controller="Providers" asp-action="CreateAsync" class="form p-t-20" method="post" role="form">
                <div class="row">
                    <div class="col-md-6">
                        <div class="form-group">
                            <label asp-for="FullName">Provider Name</label>
                            <div class="input-group">
                                <div class="input-group-addon"><i class="ti-user"></i></div>
                                <input asp-for="FullName" class="form-control" placeholder="Enter Provider Name" required>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="form-group">
                            <label asp-for="TrainerType" class="control-label">Type of Training Provider</label>
                            <select asp-for="TrainerType" class="form-control custom-select" data-placeholder="Choose a Type of Provider">
                                <option value="Institution">Training Institution</option>
                                <option value="MasterCraftsMan">Master Craftsman</option>
                            </select>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-6">
                        <div class="form-group">
                            <label asp-for="StreetRoad">Street/Road Name</label>
                            <div class="input-group">
                                <div class="input-group-addon"><i class="fa fa-road"></i></div>
                                <input asp-for="StreetRoad" class="form-control" id="StreetRoad" placeholder="Enter Street/Road" required>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="form-group">
                            <label asp-for="BuildingName">Building Name</label>
                            <div class="input-group">
                                <div class="input-group-addon"><i class="fa fa-building"></i></div>
                                <input asp-for="BuildingName" class="form-control" id="BuildingName" placeholder="Enter Building Name" required>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-6">
                        <div class="form-group">
                            <label asp-for="LandMark">Nearby Landmark Description</label>
                            <div class="input-group">
                                <div class="input-group-addon"><i class="fa fa-map-marker"></i></div>
                                <input asp-for="LandMark" class="form-control" id="Landmark" placeholder="Enter Landmark Description" required>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="form-group">
                            <label asp-for="CountyId" class="control-label">County</label>
                            <select asp-for="CountyId" class="form-control custom-select" data-placeholder="Choose a County">
                                @foreach (var county in @ViewBag.Counties)
                                {
                                    <option value=@county.Id>@county.Name</option>
                                }
                            </select>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-6">
                        <div class="form-group">
                            <label asp-for="ContactPersonName">Contact Person Name</label>
                            <div class="input-group">
                                <div class="input-group-addon"><i class="fa fa-id-card"></i></div>
                                <input asp-for="ContactPersonName" class="form-control" id="ContactName" placeholder="Enter Contact Name" required>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="form-group">
                            <label asp-for="ContactEmail">Contact Email address</label>
                            <div class="input-group">
                                <div class="input-group-addon"><i class="fa fa-envelope"></i></div>
                                <input asp-for="ContactEmail" class="form-control" id="ContactEmail" placeholder="Enter email" required>
                            </div>
                        </div>
                    </div>
                    
                </div>
                <div class="row">
                    <div class="col-md-6">
                        <div class="form-group">
                            <label asp-for="ContactPersonPosition">Contact Person Position</label>
                            <div class="input-group">
                                <div class="input-group-addon"><i class="fa fa-certificate"></i></div>
                                <input asp-for="ContactPersonPosition" class="form-control" id="Position" placeholder="Enter Position" required>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="form-group">
                            <label asp-for="Telephone">Telephone Number</label>
                            <div class="input-group">
                                <div class="input-group-addon"><i class="fa fa-phone"></i></div>
                                <input asp-for="Telephone" class="form-control" id="Telephone" placeholder="Enter Telephone" required>
                            </div>
                        </div>
                    </div>
                    </div>
                <div class="row">
                    <div class="col-md-6">
                        <div class="form-group">
                            <label asp-for="PostalAddress">Postal Address</label>
                            <div class="input-group">
                                <div class="input-group-addon"><i class="fa fa-address-book"></i></div>
                                <input asp-for="PostalAddress" class="form-control" id="pwd2" placeholder="Enter Postal Address" required>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-6">
                        <button type="submit" class="btn btn-success waves-effect waves-light m-r-10">Submit</button>
                        <button type="submit" class="btn btn-inverse waves-effect waves-light">Cancel</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>

com.nita/Views/Providers/CreateEmployer.cshtml
@using Nita.ViewModels.ContractViewModels;
<!-- Favicon icon -->
<link rel="icon" type="image/png" sizes="16x16" href="~/lib/images/favicon.png">
<!-- Bootstrap Core CSS -->
<link href="~/lib/plugins/bootstrap/css/bootstrap.min.css" rel="stylesheet">
<!-- Custom CSS -->
<link href="~/lib/css/style.css" rel="stylesheet">
<!-- You can change the theme colors from here -->
<link href="~/lib/css/colors/default-dark.css" id="theme" rel="stylesheet">
<div class="row"><div class="col-md-12 card"><h2>Internship Providers (Employers)</h2></div></div>
<div class="card">
    <div class="card-body">
        <h4>Step 4</h4>
        <div class="row">
            <div class="col-md-6">
                <div class="card-body">
                    <label class="control-label">Register Internship Provider:</label><br><hr>
                    <form asp-controller="Providers" asp-action="SaveEmployer" method="post">
                        <div class="row">
                            <div class="col-md-12">
                                <div class="form-group">
                                    <label class="control-label">Business Name </label>
                                    <input type="text" id="BusinessName" name="BusinessName" class="form-control">
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-12">
                                <div class="form-group">
                                    <label class="control-label">Industry </label>
                                    <input type="text" id="Industry" name="Industry" class="form-control">
                                </div>
                            </div>
                        </div>
                        <input type="number" hidden="hidden" value="@ViewBag.Id" id="Id" name="Id">
                        <div class="row">
                            <div class="col-md-12">
                                <div class="form-group">
                                    <label class="control-label">Notes </label>
                                    <input type="text" class="form-control" id="Notes" name="Notes" placeholder="Enter Notes" required>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-12">
                            <div class="form-group">
                                <label class="control-label">Choose a County </label>
                                <select class="form-control" id="CountyId" name="CountyId">
                                    @foreach (var county in @ViewBag.Counties)
                                    {
                                        <option value=@county.Id>@county.Name</option>
                                    }
                                </select>
                            </div>
                            </div>
                        </div>
                            <div class="row">
                                <div class="col-md-12" style="text-align:right"><button type="submit" class="btn btn-primary"><i class="fa fa-plus">Add</i></button></div>
                            </div>
                            <hr>
                        </form>
                </div>
            </div>
            <div class="col-md-6">
                <div class="card-body">
                    <label class="control-label">Added Employer(s):</label><br><hr>
                    <div class="table-responsive">
                        <table class="table color-table primary-table">
                            <thead>
                                <tr>
                                    <th>#</th>
                                    <th>Employer Name</th>
                                    <th>Industry</th>
                                    <th><i class="fa fa-bolt"></i></th>
                                </tr>
                            </thead>
                            @if (@ViewBag.Employers != null)
                            {
                                <tbody>
                                    @foreach (var employer in @ViewBag.Employers)
                                    {
                                        <tr>
                                            <td>@employer.Id</td>
                                            <td>@employer.Name</td>
                                            <td>@employer.Industry</td>
                                            <td><a href="@Url.Action("removeEmployer","Providers",new {contractId = ViewBag.Id})" class="btn btn-danger btn-xs"><i class="fa fa-times"></i></a></td>
                                        </tr>
                                    }
                                </tbody>
                            }
                            else
                            {
                                <tbody>
                                    <tr><td><h6>There are no employers</h6></td></tr>
                                </tbody>

                            }
                        </table>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12" style="text-align:right;">
                <a href="@Url.Action("Index","Providers")" class="btn btn-primary">Finish</a>
            </div>
        </div>
    </div>

</div>


@section Scripts
    {
    <script>
    </script>
    <script src="~/lib/plugins/bootstrap/js/bootstrap.min.js"></script>
    @*<script src="~/lib/plugins/jquery/jquery.min.js"></script>*@
    <script src="~/lib/plugins/bootstrap/js/popper.min.js"></script>
}

com.nita/Views/Providers/Delete.cshtml
@{
    ViewData["Title"] = "Delete";
}

<h2>Delete</h2>

com.nita/Views/Providers/Details.cshtml
@{
    ViewData["Title"] = "Details";
}

<h2>Details</h2>