com.nita/Controllers/BudgetController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using com.nita.IdentityModels;
using com.nita.Settings;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Options;
using Nita.ViewModels.BudgetViewModels;

namespace Nita.Controllers
{
    [Authorize]
    public class BudgetController : Controller
    {
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly IHostingEnvironment _hostingEnvironment;
        private readonly IOptions<AppSettings> _appSettings;
        private readonly IServiceProvider _provider;
        // GET: Contracts

        public BudgetController(
            IServiceProvider prov,
            IHostingEnvironment env,
            IOptions<AppSettings> appSettings, UserManager<ApplicationUser> userManager)
        {
            this._provider = prov;
            this._appSettings = appSettings;
            this._hostingEnvironment = env;
            this._userManager = userManager;
        }
        public IActionResult Index(int? cycleId,int? deptId)
        {
            var cId = Convert.ToInt32(cycleId);
            var dId = Convert.ToInt32(deptId);
            
            var db = _provider.GetRequiredService<ApplicationDbContext>();
            List<VoteHead> voteList = new List<VoteHead>();
            var periods = db.BudgetPeriod.ToList();
            var items=new List<FinanceBudget>();
            if (cId!=0 && dId!=0)
            {
                var bPeriods = db.BudgetPeriod.Where(p => p.FYId == cId).ToList();
                foreach (var bPeriod in bPeriods)
                {
                    var periodItems = db.FBudgets.Where(f => f.PeriodId == bPeriod.Id && f.DeptId == dId).ToList();
                    items.AddRange(periodItems);
                }

                var bCycles = db.Cycles.Where(c => c.FYId == cId).ToList();
                foreach (var bCycle in bCycles)
                {
                    var cycleItems = db.FBudgets.Where(f => f.CycleId == bCycle.Id && f.DeptId == dId).ToList();
                    items.AddRange(cycleItems);
                }
                //items = db.FBudgets.Where(f => f.YearId == cId && f.DeptId == dId).ToList();
                ViewBag.Message = db.FiscalYears.Single(c => c.Id == cId).Name + " Fiscal Year | " + db.HrDepartments.Single(d => d.Id == dId).Name+" Department Budget Items";
                ViewBag.dId = dId;
                ViewBag.yId = cId;
            }else if (cId!=0 && dId==0)
            {
                var bPeriods = db.BudgetPeriod.Distinct().Where(p => p.FYId == cId).ToList();
                foreach (var bPeriod in bPeriods)
                {
                    var periodItems = db.FBudgets.Where(f => f.PeriodId == bPeriod.Id).ToList();
                    items.AddRange(periodItems);
                }

                var bCycles = db.Cycles.Where(c => c.FYId == cId).ToList();
                foreach (var bCycle in bCycles)
                {
                    var cycleItems = db.FBudgets.Where(f => f.CycleId == bCycle.Id).ToList();
                    items.AddRange(cycleItems);
                }
                //items = db.FBudgets.Where(x => x.YearId == cId).ToList();
                ViewBag.Message = db.FiscalYears.Single(c => c.Id == cId).Name + " Fiscal Year | " +  "All Department(s) Budget Items";
                ViewBag.dId = 0;
                ViewBag.yId = cId;
            }
            else if (cId == 0 && dId != 0)
            {
                items = db.FBudgets.Where(x => x.DeptId == dId).ToList();
                ViewBag.Message =  "All Fiscal Year(s) | " + db.HrDepartments.Single(c => c.Id == dId).Name + " Department(s) Budget Items";
                ViewBag.dId = dId;
                ViewBag.yId = 0;
            }
            else
            {
                items = db.FBudgets.ToList();
                ViewBag.Message = "All Financial Years | All Departments Budget Items";
                ViewBag.dId = 0;
                ViewBag.yId = 0;
            }

            var distinctItems = items.GroupBy(x => x.Id).Select(y => y.First());

            foreach (var item in distinctItems)
            {
                var vote = new VoteHead()
                {
                   Number = item.Id,
                   AccName = db.FinanceAccounts.Single(a=>a.Id == item.AccountId).Name.ToString(),
                   Amount = item.Amount,
                    Enforced = item.Enforced
                };
                voteList.Add(vote);
            }
            var accounts = db.FinanceAccounts.ToList();
            var departments = db.HrDepartments.ToList();
            var fYears = db.FiscalYears.ToList();
            var cycles = db.Cycles.ToList();
            ViewBag.Periods = periods;
            ViewBag.VoteHeads = voteList;
            ViewBag.Accounts = accounts;
            ViewBag.Departments = departments;
            ViewBag.FYears = fYears;
            ViewBag.Cycles = cycles;
            return View();
        }

        public ActionResult MainBudget(int? yId)
        {
            var db = _provider.GetRequiredService<ApplicationDbContext>();
            List<MainBudgetItem> mainBudgetItems = new List<MainBudgetItem>();
            var accounts = db.FinanceAccounts.ToList();
            var total = 0.0;
            if (yId == 0 || yId == null)
            {
                
                foreach (var account in accounts)
                {
                    var accountItems = db.FBudgets.Where(a => a.AccountId == account.Id).ToList();
                    var sum = 0.0;
                    foreach (var accItem in accountItems)
                    {
                        sum += accItem.Amount;
                    }


                    mainBudgetItems.Add(new MainBudgetItem()
                    {
                        Id = account.Id,
                        Name = account.Name,
                        Amount = sum
                    });
                    total += sum;
                }

                ViewBag.Total = total;
                ViewBag.Message = "All Fiscal Years Budget";
            }
            else
            {
                foreach (var account in accounts)
                {
                    var accountItems = db.FBudgets.Where(a => a.AccountId == account.Id).ToList();
                    var sum = 0.0;
                    foreach (var accItem in accountItems)
                    {
                            if (accItem.CycleId != 0)
                            {
                                var response = db.Cycles.Where(c => c.Id == accItem.CycleId).FirstOrDefault();
                                if (response != null)
                                {
                                    var cyid = response.FYId;
                                    if (cyid == yId)
                                    {
                                        sum += accItem.Amount;
                                    }
                            }
                                else
                                {
                                sum += 0;
                            }
                            }
                            else
                            {
                                var response = db.BudgetPeriod.Where(c => c.Id == accItem.PeriodId).First();
                                if (response != null)
                                {
                                    var pyid = response.FYId;
                                    if (pyid == yId)
                                    {
                                        sum += accItem.Amount;
                                    }
                            }
                                else
                                {
                                    sum += 0;
                            }
                            }
                            
                        
                    }

                    mainBudgetItems.Add(new MainBudgetItem()
                    {
                        Id = account.Id,
                        Name = account.Name,
                        Amount = sum
                    });
                    total += sum;
                }
                ViewBag.Total = total;
                ViewBag.fyId = yId;
                ViewBag.Message = db.FiscalYears.Single(f=>f.Id == yId).Name+" Fiscal Year Budget";
            }

            var fYears = db.FiscalYears.ToList();
            ViewBag.FYears = fYears;
            ViewBag.MainBudgetItems = mainBudgetItems;
            return View();
        }

        public ActionResult BudgetPeriod(int? errorCode)
        {
            if (errorCode != 0 && errorCode != null)
            {
                var error = Convert.ToInt32(errorCode);
                if (error == 1)
                {
                    ViewBag.Error = 1;
                    ViewBag.DateMessage = "Start Date must fall within the fiscal year dates";
                }
                if (error == 2)
                {
                    ViewBag.Error = 2;
                    ViewBag.DateMessage = "End Date must fall within the fiscal year";
                }

                if (error == 3)
                {
                    ViewBag.Error = 3;
                    ViewBag.DateMessage = "Period Cannot be deleted because it has some related records";
                }
            }
            var db = _provider.GetRequiredService<ApplicationDbContext>();
            var fYears = db.FiscalYears.ToList();
            var periods = db.BudgetPeriod.ToList();
            ViewBag.FYears = fYears;
            ViewBag.Periods = periods;
            return View();
        }

        public ActionResult Create(BudgetItem budgetItem)
        {

com.nita/Views/Budget/BudgetPeriod.cshtml
<!-- Favicon icon -->
<link rel="icon" type="image/png" sizes="16x16" href="~/lib/images/favicon.png">
<!-- Bootstrap Core CSS -->
<link href="~/lib/plugins/bootstrap/css/bootstrap.min.css" rel="stylesheet">
<!-- Custom CSS -->
<link href="~/lib/css/style.css" rel="stylesheet">
<!-- You can change the theme colors from here -->
<link href="~/lib/css/colors/default-dark.css" id="theme" rel="stylesheet">

<div class="row"><div class="col-md-12 card"><h2>Budget Periods Management</h2></div></div>
<div class="row">
    <div class="col-md-11" style="text-align: right">
        <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal" data-whatever=""><i class="fa fa-plus">Add Period</i></button>
        @*<button type="button" class="btn btn-primary" id="addTp"><i class="fa fa-plus"></i> Add Contract</button>*@
    </div>
    <div class="col-md-1"></div>
</div>
@if (@ViewBag.Error != 0 && @ViewBag.Error != null)
{
    <div class="row">
        <div class="col-md-6">
            <div class="alert alert-danger">
                <strong>Error!</strong> @ViewBag.DateMessage
            </div>
        </div>
        <div class="col-md-6"></div>
    </div>
}
<div class="card">
    <div class="card-body">
        <div class="row">
            <div class="col-md-12">
                <table class="table table-striped table-bordered" id="editable-datatable">
                    <thead>
                        <tr>
                            <th>#</th>
                            <th>Period Name</th>
                            <th>Period From</th>
                            <th>Period To</th>
                            <th>Action</th>
                        </tr>
                    </thead>
                    @if (@ViewBag.Periods != null)
                    {
                        <tbody>
                            @foreach (var period in @ViewBag.Periods)
                            {
                                <tr>
                                    <td>@period.Id</td>
                                    <td>@period.PeriodName</td>
                                    <td>@period.PeriodFrom.ToString("dd MMM yyyy")</td>
                                    <td>@period.PeriodTo.ToString("dd MMM yyyy")</td>
                                    <td>
                                        <button class="btn btn-warning btn-sharp-corners btn-xs edit" id=@period.Id name=@period.Id data-toggle="tooltip" title="Edit Cycle"><i class="fa fa-edit"></i></button>
                                        <a class="btn btn-danger btn-sharp-corners btn-xs delete" href="@Url.Action("DeletePeriod","Budget",new{id=@period.Id})" id=@period.Id name=@period.Id data-toggle="tooltip" title="Delete Cycle"><i class="fa fa-times"></i></a>
                                    </td>
                                </tr>
                            }
                        </tbody>
                    }
                    else
                    {
                        <tbody>
                            <tr><td><h6>There are no Periods</h6></td></tr>
                        </tbody>

                    }
                </table>
            </div>
        </div>
    </div>
</div>
<!--training provider modal-->
<!-- Modal -->
<div class="modal fade" id="exampleModal" role="dialog" style="overflow-y: scroll; max-height:85%;  margin-top: 50px; margin-bottom:50px;">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title" id="exampleModalLabel1">Create a Budget Period</h4>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            </div>
            <form asp-controller="Budget" asp-action="SavePeriod" class="form p-t-20" method="post" role="form">
                <div class="modal-body">
                    <input type="hidden" id="PeriodId" name="PeriodId" value="0">
                    <div class="form-group">
                        <label for="PeriodName" class="control-label">Period Name:</label>
                        <input type="text" class="form-control" id="PeriodName" name="PeriodName" placeholder="Enter Period Name">
                    </div>
                    <div class="row">
                        <div class="col-md-12">
                            <label for="StartDate" class="control-label">Period Start Date:</label>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-4">
                            <div class="form-group">
                                <label for="recipient-name" class="control-label">Day:</label>
                                <select class="form-control" id="Day" name="Day" data-placeholder="--Day--">
                                    @for (int i = 1; i <= 30; i++)
                                    {
                                        if (i < 10)
                                        {
                                            <option value=@i>@i</option>
                                        }
                                        else
                                        {
                                            <option value=@i>@i</option>
                                        }
                                    }
                                </select>
                            </div>
                        </div>
                        <div class="col-md-4">
                            <div class="form-group">
                                <label for="recipient-name" class="control-label">Month:</label>
                                <select class="form-control" id="Month" name="Month" data-placeholder="--Month--">
                                    @for (int i = 1; i <= 12; i++)
                                    {
                                        <option value=@i>@i</option>
                                    }
                                </select>
                            </div>
                        </div>
                        <div class="col-md-4">
                            <div class="form-group">
                                <label for="recipient-name" class="control-label">Year:</label>
                                <select class="form-control" id="Year" name="Year" data-placeholder="--Year--">
                                    @for (int i = 2017; i <= 2050; i++)
                                    {
                                        <option value=@i>@i</option>
                                    }
                                </select>
                            </div>
                        </div>
                    </div>

                    <div class="row">
                        <div class="col-md-12">
                            <label for="EndDate" class="control-label">Period End Date:</label>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-4">
                            <div class="form-group">
                                <label for="recipient-name" class="control-label">Day:</label>
                                <select class="form-control" id="Day1" name="Day1" data-placeholder="--Day--">
                                    @for (int i = 1; i <= 30; i++)
                                    {
                                        <option value=@i>@i</option>
                                    }
                                </select>
                            </div>
                        </div>
                        <div class="col-md-4">
                            <div class="form-group">
                                <label for="recipient-name" class="control-label">Month:</label>
                                <select class="form-control" id="Month1" name="Month1" data-placeholder="--Month--">
                                    @for (int i = 1; i <= 12; i++)
                                    {
                                        <option value=@i>@i</option>
                                    }
                                </select>
                            </div>
                        </div>
                        <div class="col-md-4">
                            <div class="form-group">
                                <label for="recipient-name" class="control-label">Year:</label>
                                <select class="form-control" id="Year1" name="Year1" data-placeholder="--Year--">
                                    @for (int i = 2017; i <= 2050; i++)
                                    {
                                        <option value=@i>@i</option>
                                    }
                                </select>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-12">
                            <div class="form-group">
                                <label for="yearId" class="control-label">Fiscal Year</label>
                                <select for="YearId" name="YearId" id="YearId" class="form-control" data-placeholder="Choose a Fiscal Year">
                                    @foreach (var year in @ViewBag.FYears)
                                    {
                                        <option value=@year.Id>@year.Name</option>
                                    }
                                </select>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                    <button type="submit" class="btn btn-primary">Save</button>
                </div>
            </form>
        </div>
    </div>
</div>

@section Scripts
    {

    <script>
        $(document).ready(function () {
            $(".edit").click(function () {
                //alert("WE should be working");

            $.ajax({
                type: 'GET',
                url: '@Url.Action("EditPeriod", "Budget")',
                dataType: 'json',
                data: {
                    id: this.id
                },
                success: function (data) {
                    //alert("meeh");
                    $('#exampleModal').modal('show');
                    console.log(data);
                    $('#PeriodId').val(data.id);
                    $('#PeriodName').val(data.name);
                    $('#YearId').val(data.yearId).change();
                    $('#Day').val(data.day).change();
                    $('#Month').val(data.month).change();
                    $('#Year').val(data.year).change();
                    $('#Day1').val(data.day1).change();
                    $('#Month1').val(data.month1).change();
                    $('#Year1').val(data.year1).change();
                },
                error: function (data) {
                    alert("There was problems there");
                }
                });
            });
        });
    </script>

    <script src="~/lib/plugins/bootstrap/js/bootstrap.min.js"></script>
    @*<script src="~/lib/plugins/jquery/jquery.min.js"></script>*@
    <script src="~/lib/plugins/bootstrap/js/popper.min.js"></script>
    <!-- Footable -->
    <script src="~/lib/plugins/footable/js/footable.all.min.js"></script>
    <script src="~/lib/plugins/bootstrap-select/bootstrap-select.min.js" type="text/javascript"></script>
    <!--FooTable init-->
    <script src="~/lib/js/footable-init.js"></script>
    <!-- Editable -->
    <script src="~/lib/plugins/jquery-datatables-editable/jquery.dataTables.js"></script>
    <script src="~/lib/plugins/datatables/dataTables.bootstrap.js"></script>
    <script src="~/lib/plugins/tiny-editable/mindmup-editabletable.js"></script>
    <script src="~/lib/plugins/tiny-editable/numeric-input-example.js"></script>
    <script>
        jQuery('#mainTable').editableTableWidget().numericInputExample().find('td:first').focus();
        jQuery('#editable-datatable').editableTableWidget().numericInputExample().find('td:first').focus();
        jQuery(document).ready(function () {
            jQuery('#editable-datatable').DataTable();
        });
    </script>
    <script>
        jQuery('#add-yr').click(function () {
            window.location = jQuery(this).data('target');
        });
        jQuery('#add-q-yr').click(function () {
            window.location = jQuery(this).data('target');
        });
    </script>
    <script type="text/javascript">
        $(function () {
            $(".preloader").fadeOut();
        });

    </script>
}

com.nita/Views/Budget/MainBudget.cshtml
@model Nita.ViewModels.BudgetViewModels.BudgetItem;
<!-- Favicon icon -->
<link rel="icon" type="image/png" sizes="16x16" href="~/lib/images/favicon.png">
<!-- Bootstrap Core CSS -->
<link href="~/lib/plugins/bootstrap/css/bootstrap.min.css" rel="stylesheet">
<!-- Custom CSS -->
<link href="~/lib/css/style.css" rel="stylesheet">
<!-- You can change the theme colors from here -->
<link href="~/lib/css/colors/default-dark.css" id="theme" rel="stylesheet">
<link href="~/lib/plugins/wizard/steps.css" rel="stylesheet">
<!--alerts CSS -->
<link href="~/lib/plugins/sweetalert/sweetalert.css" rel="stylesheet" type="text/css">
<!-- Bootstrap responsive table CSS -->
<link href="~/lib/plugins/tablesaw-master/dist/tablesaw.css" rel="stylesheet">
<!-- Bootstrap responsive table CSS -->
<link href="~/lib/plugins/tablesaw-master/dist/tablesaw.css" rel="stylesheet">

<div class="row"><div class="col-md-12 card"><h2>Main Budget</h2></div></div>

<div class="card">
    <div class="card-body">
        <h4 class="card-title">Main Budget</h4>
        <h6 class="card-subtitle">Main Budget Items</h6>
        <div class="row">
            <div class="col-md-4"></div>
            <div class="col-md-8">
                <form asp-controller="Budget" asp-action="MainBudget" class="form p-t-20" method="get" role="form">
                    <div class="row">
                        <div class="col-md-1"></div>
                        <div class="col-md-3">
                            <div class="form-group">
                                <label class="control-label">Select Fiscal Year </label>
                                <select class="form-control" id="yId" name="yId">
                                    <option value="0">All</option>
                                    @foreach (var years in @ViewBag.FYears)
                                    {
                                        if (@years.Id == @ViewBag.fyId)
                                        {
                                            <option value=@years.Id selected="selected">@years.Name</option>
                                        }
                                        else
                                        {
                                            <option value=@years.Id>@years.Name</option>
                                        }
                                    }
                                </select>
                            </div>
                        </div>
                        <div class="col-md-4">
                            <div class="form-group">
                                <label class="control-label">Generate  </label><br/>
                                <button type="submit" class="btn btn-primary" id="addTp"><i class="fa fa-cogs"></i> Generate</button>
                            </div>
                        </div>

                    </div>
                </form>
            </div>
        </div>
        
        <div class="table-responsive m-t-40">
            <span class="alert alert-dark">@ViewBag.Message</span>
            <table id="myTable" class="table table-bordered table-striped">
                <thead>
                <tr>
                    <th>No.</th>
                    <th>Account Name</th>
                    <th>Amount</th>
                </tr>
                </thead>
                <tbody>
                @foreach (var items in @ViewBag.MainBudgetItems)
                {
                    <tr>
                        <td>@items.Id</td>
                        <td>@items.Name</td>
                        <td>@items.Amount</td>
                    </tr>
                }
                    <tr><td></td><td style="text-align: right">Total:</td><td><span class="badge-pill"> @ViewBag.Total </span></td></tr>
                </tbody>
            </table>
                
        </div>
    </div>
</div>


@section Scripts
    {
    <script src="~/lib/plugins/bootstrap/js/bootstrap.min.js"></script>
    @*<script src="~/lib/plugins/jquery/jquery.min.js"></script>*@
    <script src="~/lib/plugins/bootstrap/js/popper.min.js"></script>
    <script>
        $(document).ready(function () {
            $('#myTable').DataTable();
            $(document).ready(function () {
                var table = $('#example').DataTable({
                    "columnDefs": [{
                        "visible": false,
                        "targets": 2
                    }],
                    "order": [
                        [2, 'asc']
                    ],
                    "displayLength": 25,
                    "drawCallback": function (settings) {
                        var api = this.api();
                        var rows = api.rows({
                            page: 'current'
                        }).nodes();
                        var last = null;
                        api.column(2, {
                            page: 'current'
                        }).data().each(function (group, i) {
                            if (last !== group) {
                                $(rows).eq(i).before('<tr class="group"><td colspan="5">' + group + '</td></tr>');
                                last = group;
                            }
                        });
                    }
                });
                // Order by the grouping
                $('#example tbody').on('click', 'tr.group', function () {
                    var currentOrder = table.order()[0];
                    if (currentOrder[0] === 2 && currentOrder[1] === 'asc') {
                        table.order([2, 'desc']).draw();
                    } else {
                        table.order([2, 'asc']).draw();
                    }
                });
            });
        });
        $('#example23').DataTable({
            dom: 'Bfrtip',
            buttons: [
                'copy', 'csv', 'excel', 'pdf', 'print'
            ]
        });
    </script>
}