com.nita/Controllers/CyclesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using com.nita.IdentityModels;
using com.nita.Settings;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Options;
using Nita.ViewModels.CycleViewModels;
using OfficeOpenXml.FormulaParsing.Excel.Functions.DateTime;

namespace Nita.Controllers
{
    [Authorize]
    public class CyclesController : Controller
    {
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly IOptions<AppSettings> appSettings;
        private readonly IServiceProvider provider;
        private readonly IHostingEnvironment hostingEnvironment;
        // GET: Cycles
        public CyclesController(
           IServiceProvider prov,
           IHostingEnvironment env,
           IOptions<AppSettings> appSettings, UserManager<ApplicationUser> userManager)
        {
            this.provider = prov;
            this.appSettings = appSettings;
            this.hostingEnvironment = env;
            this._userManager = userManager;
        }
        public ActionResult Index(int? errorCode )
        {
            if (errorCode != 0 && errorCode != null)
            {
                var error = Convert.ToInt32(errorCode);
                if (error == 1)
                {
                    ViewBag.Error = 1;
                    ViewBag.DateMessage = "Start Date must fall within the fiscal year dates";
                }
                if (error == 2)
                {
                    ViewBag.Error = 2;
                    ViewBag.DateMessage = "End Date must fall within the fiscal year";
                }
                if (error == 3)
                {
                    ViewBag.Error = 3;
                    ViewBag.DateMessage = "Cannot Delete cycle because it has some related records";
                }
            }

            var db = provider.GetRequiredService<ApplicationDbContext>();
            var cycles = db.Cycles.ToList();
            var fYears = db.FiscalYears.ToList();
            ViewBag.FYears = fYears;
            ViewBag.Cycles = cycles;
            return View();
        }

        // GET: Cycles/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Cycles/Create
        //public ActionResult Create()
        //{
        //    return View();
        //}

        // POST: Cycles/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> SaveData(CycleModel cycleModel)
        {
            try
            {
                // TODO: Add insert logic here
                var db = provider.GetRequiredService<ApplicationDbContext>();
                var cycles = new Cycle();
                var id = cycleModel.CycleId;
                var day = cycleModel.Day;
                var month = cycleModel.Month;
                var year = cycleModel.Year;
                var date = day + "/" + month + "/" + year;
                var day1 = cycleModel.Day1;
                var month1 = cycleModel.Month1;
                var year1 = cycleModel.Year1;
                var date1 = day1 + "/" + month1 + "/" + year1;
                var startDate = Convert.ToDateTime(date);
                var endDate = Convert.ToDateTime(date1);
                var fiscalYear = db.FiscalYears.Find(cycleModel.YearId);
                if (fiscalYear.BeginDate > startDate || fiscalYear.EndDate< startDate)
                {
                     return RedirectToAction("Index", new { errorCode = 1 });
                }

                if (fiscalYear.BeginDate > endDate || fiscalYear.EndDate < endDate)
                {
                    
                    return RedirectToAction("Index", new { errorCode = 2 });
                }

                //var duration = cycleModel.Duration;
                if (id == 0)
                {
                    cycles.CycleName = cycleModel.CycleName;
                    cycles.CycleCapacity = Convert.ToInt32(cycleModel.CycleCapacity);
                    cycles.CycleFrom = startDate;
                    cycles.CycleTo = endDate;
                    cycles.FYId = cycleModel.YearId;
                     await db.Cycles.AddAsync(cycles);
                  
                    db.SaveChanges();
                    var markFlags = db.MarkEntryFlags.Add(new MarkEntryFlag
                    {
                        CycleId = cycles.Id
                    });
                    db.SaveChanges();
                }
                else {
                    var cycle = db.Cycles.Find(id);
                    cycle.CycleName = cycleModel.CycleName;
                    cycle.CycleCapacity = Convert.ToInt32(cycleModel.CycleCapacity);
                    cycle.CycleFrom = startDate;
                    cycle.CycleTo = endDate;
                    cycle.FYId = cycleModel.YearId;
                    db.SaveChanges();
                }

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return RedirectToAction(nameof(Index));
            }
        }

        // GET: Cycles/Edit/5
        [HttpGet]
        public JsonResult Edit(int id)
        {
            var db = provider.GetRequiredService<ApplicationDbContext>();
            var cycleData = db.Cycles.Find(id);
            var cid = cycleData.Id;
            var name = cycleData.CycleName;
            var capacity = cycleData.CycleCapacity;
            var day = cycleData.CycleFrom.Day.ToString();
            var month = cycleData.CycleFrom.Month.ToString();
            var year = cycleData.CycleFrom.Year.ToString();
            var day1 = cycleData.CycleTo.Day.ToString();
            var month1 = cycleData.CycleTo.Month.ToString();
            var year1 = cycleData.CycleTo.Year.ToString();
            return Json(new {cid=cid,name=name,day =day,capacity=capacity,month=month,year=year,day1 =day1,month1=month1,year1=year1});
        }

        // POST: Cycles/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: Cycles/Delete/5
        public ActionResult Delete(int id)
        {
            var db = provider.GetRequiredService<ApplicationDbContext>();
            if (db.FBudgets.Where(c=>c.CycleId == id).Any())
            {
                return RedirectToAction("Index", new { errorCode = 3 });
            }

            db.Remove(db.Cycles.Find(id));
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        // POST: Cycles/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

com.nita/Controllers/StaffController.cs
namespace com.nita.Controllers
{
    using System.Text;
    using System.Threading;
    using System.Threading.Tasks;
    using Boilerplate.AspNetCore;
    using Boilerplate.AspNetCore.Filters;
    using Microsoft.AspNetCore.Mvc;
    using Microsoft.Extensions.Options;
    using com.nita.Constants;
    using com.nita.Services;
    using com.nita.Settings;
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Hosting;
    using System.Net.Http;
    using Newtonsoft.Json.Linq;
    using System;
    using Microsoft.Extensions.DependencyInjection;
    using com.nita.IdentityModels;
    using com.nita.ViewModels;
    using Microsoft.EntityFrameworkCore;
    using Microsoft.AspNetCore.Identity;
    using Microsoft.Extensions.Logging;
    using System.Linq;

    [Authorize]
    //[Route("[controller]/[action]")]
    public sealed partial class StaffController : Controller
    {
        #region Fields
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly IOptions<AppSettings> appSettings;
        private readonly IServiceProvider provider;
        private readonly IHostingEnvironment hostingEnvironment;
        private readonly ILogger logger;
        
        #endregion

        #region Constructors

        public StaffController(
            UserManager<ApplicationUser> userManager,
            IServiceProvider prov,
            IHostingEnvironment env,
            IOptions<AppSettings> appSettings)
        {
            this.provider = prov;
            this.appSettings = appSettings;
            this.hostingEnvironment = env;
            this._userManager = userManager;

            //
            var factory = prov.GetRequiredService<ILoggerFactory>();
            logger = factory.CreateLogger<StaffController>();
        }

        #endregion
        /// <summary>
        /// 
        /// </summary>
        /// <returns></returns>
        [HttpGet("staff", Name = StaffControllerRoute.GetIndex)]
        public IActionResult Index()
        {
            

            return this.View(StaffControllerAction.Index);
        }
        /// <summary>
        /// 
        /// </summary>
        /// <returns></returns>
        [HttpGet("allstaff", Name = StaffControllerRoute.GetAllStaff)]
        public IActionResult AllStaff()
        {
            if (Request.Query.Any(p => p.Key.Equals("msg")))
            {
                ViewData["Message"] = Request.Query.First(k => k.Key.Equals("msg")).Value;
            }
            //
            return this.View(StaffControllerAction.AllStaff);
        }
        /// <summary>
        /// 
        /// </summary>
        /// <returns></returns>
        [HttpGet("addstaff", Name = StaffControllerRoute.AddStaff)]
        public IActionResult AddStaff()
        {
            var model = new AddStaffViewModel();
            

            return this.View(StaffControllerAction.AddStaff,model);
        }
        /// <summary>
        /// 
        /// </summary>
        /// <param name="model"></param>
        /// <returns></returns>
        [HttpPost("addstaff", Name = StaffControllerRoute.AddStaff)]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AddStaff(AddStaffViewModel model)
        {
            //
            if (ModelState.IsValid)
            {
                //App USer
                var user = new ApplicationUser()
                {
                    UserName = model.EmployeeNumber,
                    Email = model.PersonalEmail,
                    PhoneNumber = model.PhoneNumber,
                    AccountType = AccountType.NitaStaff
                };

                //Create USer Account
                var result = await _userManager.CreateAsync(user, appSettings.Value.DefaultPassword);
                logger.LogInformation(1, "Crated Account "+user.UserName);
                if (result.Succeeded)
                {
                    try
                    {
                        //
                        var db = provider.GetRequiredService<ApplicationDbContext>();

                        BankBranch branch = null;
                        var br = db.PBanks.Include(l => l.Branches).Select(p => p.Branches.Single(l => l.Id == model.BankBranchId));
                        if (!br.Any())
                        {
                            ModelState.AddModelError(string.Empty, "Please select a valid bank branch and try again.");
                            return this.View();
                        }
                        else
                        {
                            branch = br.First();
                        }
                        //County
                        var county = await db.Counties.SingleAsync(j => j.Id == model.County);
                        //address
                        var address = new UserAddress();
                        address.City = model.City;
                        address.CountyId = county.Id;
                        address.Nationality = model.Citizenship;
                        address.PAddress = model.Address;
                        address.PostalCode = model.PostalCode;
                        address.Street = model.Street;
                        address.WEmail = model.WorkEmail;
                        //Add
                        db.Addresses.Add(address);
                        db.SaveChanges();

                        //Bank Account
                        var bacc = new BankAccount()
                        {
                            Name = model.BankAccName,
                            Number = model.BankAccNo,
                            BranchId = branch.Id
                        };
                        db.PBankAccounts.Add(bacc);
                        db.SaveChanges();
                        //Staff
                        var staffProfile = new StaffProfile();
                        staffProfile.FullName = model.FullName;
                        //Salutation
                        staffProfile.Title = model.Title == (int)Title.Hon ? Title.Hon :
                            model.Title == (int)Title.Miss ? Title.Miss :
                            model.Title == (int)Title.Mr ? Title.Mr :
                            model.Title == (int)Title.Mrs ? Title.Mrs :
                            model.Title == (int)Title.Rev ? Title.Rev :
                            model.Title == (int)Title.Sr ? Title.Sr : Title.Other;

                        //HR Details;
                        //
                        staffProfile.EmplNo = model.EmployeeNumber;
                        //
                        staffProfile.KraPin = model.KraPIN;
                        staffProfile.LicClass = model.LicClass;
                        staffProfile.LicExp = model.LicExpirery;
                        staffProfile.LicNo = model.LicNo;
                        //Marital
                        staffProfile.Marital = model.MaritalStatus == (int)MaritalStatus.Diforced ? MaritalStatus.Diforced :
                            model.MaritalStatus == (int)MaritalStatus.Enganged ? MaritalStatus.Enganged :
                            model.MaritalStatus == (int)MaritalStatus.Married ? MaritalStatus.Married :
                            model.MaritalStatus == (int)MaritalStatus.Single ? MaritalStatus.Single :
                            model.MaritalStatus == (int)MaritalStatus.Windowed ? MaritalStatus.Windowed : MaritalStatus.Unspecified;
                        //
                        staffProfile.Nhif = model.NHIF;
                        staffProfile.Nssf = model.NSSF;
                        //Religiion
                        staffProfile.Religion = (model.ReligionId == (int)Religion.Christian ? Religion.Christian :
                            model.ReligionId == (int)Religion.Muslim ? Religion.Muslim :
                            model.ReligionId == (int)Religion.Hindu ? Religion.Hindu : Religion.Other);
                       
                        //
                        //REFRENCES
                        staffProfile.ApplicationUserId = user.Id;
                        //Section
                        var sect = await db.HrSections.SingleAsync(k => k.Id == model.SectionId);
                        staffProfile.SectionId = sect.Id;
                        //Employee Type
                        var empTyp = await db.HrEmployeeCategories.SingleAsync(k => k.Id == model.EmployeeCategory);
                        staffProfile.EmpCatId = empTyp.Id;
                        //Job catalogue
                        var jobCat = db.HrJobCatalogues.Single(p => p.Id == model.JobTitle);
                        staffProfile.JobCatId = jobCat.Id;
                        //Job Type
                        var lvGrp = db.HrLeaveGroups.First();
                        staffProfile.LeaveGroupId = lvGrp.Id;
                        //Designation
                        var desig = db.HrDesignations.Single(l => l.Id == model.Designation);
                        staffProfile.DesignationId = desig.Id;
                        //
                        if (model.Supervisor > 0)
                        {
                            var supervisor = db.HrStaff.SingleAsync(p => p.Id == model.Supervisor);
                            staffProfile.SupervisorId = supervisor.Id;
                        }
                        //
                        logger.LogInformation(1, "Updating user staff profile..");
                        user.StaffProfile = staffProfile;

                        //
                        staffProfile.BankAccId = bacc.Id;
                        staffProfile.AddressId = address.Id;
                        //
                        
                        //
                        result = await _userManager.UpdateAsync(user);
                        //
                        user = db.Users.Include(k=>k.StaffProfile).Single(p => p.Id == user.Id);

com.nita/Views/Shared/TempLayout.cshtml
@RenderBody()

com.nita/Views/Shared/TokenView.cshtml
@{ 
    Layout = "TempLayout";
}
@Html.AntiForgeryToken()

com.nita/Views/Shared/_AsidePartial.cshtml
@using Microsoft.EntityFrameworkCore;

@inject IOptionsSnapshot<AppSettings> AppSettings
@inject ApplicationDbContext db
@{
    var UserName = User.Identity.Name;

    var usr = db.Users.Include(l => l.StaffProfile).Include(k => k.AdminProfile).Single(p => p.UserName == UserName);
    if (usr.AccountType == AccountType.NitaAdmin)
    {
        UserName = usr.AdminProfile.FullName;
    }
    else if (usr.AccountType == AccountType.NitaStaff)
    {
        UserName = usr.StaffProfile.FullName;
    }
    else
    {
        UserName = "????????????";
    }
}

<!-- Sidebar scroll-->
<div class="scroll-sidebar"  style="">
    <!-- Sidebar navigation-->
    <nav class="sidebar-nav">
        <ul id="sidebarnav">
            <li>
                <a class=" waves-effect waves-dark" href="/" aria-expanded="false">
                    <i class="fa fa-graduation-cap"></i> <span class="hide-menu">Dashboard </span>
                </a>
            </li>
            <li class="nav-devider"></li>
            @*<li class="nav-small-cap">Menu</li>*@
            <li>
                <a class=" waves-effect waves-dark" href="@Url.Action("Index", "Cycles")" aria-expanded="false">
                    <i class="fa fa-recycle"></i> <span class="hide-menu">Cycles Management</span>
                </a>
            </li>
            <li>
                <a class=" waves-effect waves-dark" href="@Url.Action("AllStaff", "Staff")" aria-expanded="false">
                    <i class="fa fa-users"></i> <span class="hide-menu">Staff Management</span>
                </a>
            </li>
            <li>
                <a class=" waves-effect waves-dark" href="/curriculum/index" aria-expanded="false">
                    <i class="fa fa-book"></i> <span class="hide-menu">Trade Area </span>
                </a>
            </li>
            <li>
                <a class="has-arrow waves-effect waves-dark" href="#" aria-expanded="false">
                    <i class="fa fa-pencil"></i><span class="hide-menu">Beneficiaries</span>
                </a>
                <ul aria-expanded="false" class="collapse">
                    <li>
                        <a href="@Url.Action("Index", "Beneficiary")">Beneficiaries</a>
                    </li>
                    <li>
                        <a href="@Url.Action("Index", "Academics")">Academics</a>
                    </li>
                    <li>
                        <a href="@Url.Action("Graduations", "Beneficiary")">Graduation</a>
                    </li>
                </ul>
            </li>
            <li>
                <a class="has-arrow waves-effect waves-dark" href="#" aria-expanded="false">
                    <i class="fa fa-building-o"></i><span class="hide-menu">Providers</span>
                </a>
                <ul aria-expanded="false" class="collapse">
                    <li>
                        <a class="waves-effect waves-dark" href="@Url.Action("Index", "Providers")" aria-expanded="false">
                            <i class="fa fa-institution"></i> <span class="hide-menu">Institutions </span>
                        </a>
                    </li>
                    <li>
                        <a class="waves-effect waves-dark" href="@Url.Action("IndexMc", "Providers")" aria-expanded="false">
                            <i class="fa fa-wrench"></i> <span class="hide-menu">Master Craftsmen </span>
                        </a>
                    </li>
                    <li>
                        <a class=" waves-effect waves-dark" href="@Url.Action("Index", "Contracts")" aria-expanded="false">
                            <i class="fa fa-file-text"></i> <span class="hide-menu">Contracts </span>
                        </a>
                    </li>
                </ul>
            </li>
            <li>
                <a class="has-arrow waves-effect waves-dark" href="#" aria-expanded="false">
                    <i class="fa fa-tasks"></i><span class="hide-menu">Budget</span>
                </a>
                <ul aria-expanded="false" class="collapse">
                    <li>
                        <a class="waves-effect waves-dark" href="@Url.Action("BudgetPeriod", "Budget")" aria-expanded="false">
                            <i class="fa fa-clock-o"></i> <span class="hide-menu">Budget Periods</span>
                        </a>
                    </li>
                    <li>
                        <a class="waves-effect waves-dark" href="@Url.Action("Index", "Budget")" aria-expanded="false">
                            <i class="fa fa-usd"></i> <span class="hide-menu">Department Budget </span>
                        </a>
                    </li>
                    <li>
                        <a class="waves-effect waves-dark" href="@Url.Action("MainBudget", "Budget")" aria-expanded="false">
                            <i class="fa fa-address-book-o"></i> <span class="hide-menu">Main Budget </span>
                        </a>
                    </li>
                </ul>
            </li>
            @{ Html.RenderPartial("_HrMenus"); }
            @{ Html.RenderPartial("_PayrollMenus"); }
            @{ Html.RenderPartial("_FinanceMenus"); }
            @{ Html.RenderPartial("_SettingsMenus"); }
        </ul>
    </nav>
    <!-- End Sidebar navigation -->

</div>
<!-- End Sidebar scroll-->

com.nita/Views/Shared/_FooterPartial.cshtml
@inject IOptionsSnapshot<AppSettings> AppSettings


<footer class="footer"> 
    <img src="~/img/nita-logo.jpg" height="48" class="img-circle" /> &copy; @DateTime.Now.Year - @AppSettings.Value.SiteTitle
    <div style="display:inline;float:right;line-height:22px;font-family:'Trebuchet MS'"><span>Powered By:</span> <a href="http://tri-globe.com/">Triglobe Soft Solutions</a>
        </div> 
</footer>

com.nita/Views/Shared/_HrMenus.cshtml
@*Bourne Koloh*@
<li>
    <a class="has-arrow waves-effect waves-dark" href="javascript:void()" aria-expanded="false">
        <i class="fa fa-users"></i> <span class="hide-menu">Human Resource </span>
    </a>
    <ul aria-expanded="false" class="collapse">
        <li>
            <a href="@Url.RouteUrl(StaffControllerRoute.GetIndex)">Overview</a>
        </li>
        <li>
            <a href="@Url.RouteUrl(StaffControllerRoute.GetAllStaff)">All Staff</a>
        </li>
        <li>
            <a class="has-arrow waves-effect waves-dark" href="javascript:void(0)">Settings</a>
        </li>
        <li>
            <a class="has-arrow waves-effect waves-dark" href="javascript:void(0)">Utilities</a>

            <ul aria-expanded="false" class="collapse">
                <li>
                    <a href="@Url.RouteUrl(StaffUtilsControllerRoute.GetAllJobCatalogues)">Job Catalogues</a>
                </li>
                <li>
                    <a href="@Url.RouteUrl(StaffUtilsControllerRoute.GetAllEmploymentTypes)">Employment Types</a>
                </li>
                <li>
                    <a href="@Url.RouteUrl(StaffUtilsControllerRoute.GetAllJobCategories)">Job Categories</a>
                </li>
            </ul>
        </li>
    </ul>
</li>

com.nita/Views/Shared/_PayrollMenus.cshtml
@*Bourne Koloh*@
<li>
    <a class="has-arrow waves-effect waves-dark" href="@Url.RouteUrl(PayrollControllerRoute.GetIndex)" aria-expanded="false">
        <i class="fa fa-google-wallet"></i> <span class="hide-menu">Payroll </span>
    </a>
    <ul aria-expanded="false" class="collapse">
        <li>
            <a href="@Url.RouteUrl(PayrollControllerRoute.GetIndex)">Dashboard</a>
        </li>
        <li>
            <a class="has-arrow waves-effect waves-dark" href="javascript:void(0)">Process Payments</a>
            <ul aria-expanded="false" class="collapse">
                <li>
                    <a class="has-arrow waves-effect waves-dark" href="javascript:void(0)">Regular Payments</a>
                    <ul aria-expanded="false" class="collapse">
                        <li>
                            <a href="javascript:void(0)">Salary Processing</a>
                        </li>                       
                    </ul>
                </li>
                <li>
                    <a class="has-arrow waves-effect waves-dark" href="javascript:void(0)">Irregular Payments</a>
                    <ul aria-expanded="false" class="collapse">
                        <li>
                            <a href="@Url.RouteUrl(PayrollControllerRoute.GetAllIrregularPaymentVouchers)">Vouchers</a>
                        </li>
                        <li>
                            <a href="@Url.RouteUrl(PayrollControllerRoute.GetAllProcessedIrregularPayments)">Processing</a>
                        </li>
                        <li>
                            <a href="@Url.RouteUrl(PayrollControllerRoute.GetAllIrregularEarnings)">Earnings</a>
                        </li>

                        <li>
                            <a href="@Url.RouteUrl(PayrollControllerRoute.GetAllIrregularPaymentProjects)">Periods</a>
                        </li>

                        <li>
                            <a href="@Url.RouteUrl(PayrollControllerRoute.GetAllIrregularPaymentProfiles)">Payment Profiles</a>
                        </li>
                    </ul>
                </li>
            </ul>
        </li>
        @*<li>
            <a href="javascript:void(0)">Earning &amp; Deductions</a>
        </li>*@
        <li>
            <a class="waves-effect waves-dark" href="@Url.RouteUrl(PayrollControllerRoute.GetSettings)">Settings</a>            
        </li>
        <li>
            <a class="has-arrow waves-effect waves-dark" href="javascript:void(0)">Utilities</a>

            <ul aria-expanded="false" class="collapse">
                <li>
                    <a href="@Url.RouteUrl(PayrollUtilsControllerRoute.GetAllPayAccounts)">Pay Accounts</a>
                </li>

                <li>
                    <a href="@Url.RouteUrl(PayrollUtilsControllerRoute.GetAllSalaryPeriods)">Salary Periods</a>
                </li>
                <li>
                    <a href="@Url.RouteUrl(PayrollUtilsControllerRoute.GetAllPayeRates)">P.A.Y.E Rates</a>
                </li>
                <li>
                    <a href="@Url.RouteUrl(PayrollUtilsControllerRoute.GetAllNhifRates)">NHIF Rates</a>
                </li>

                <li>
                    <a href="@Url.RouteUrl(PayrollUtilsControllerRoute.GetAllJobGroups)">Job Groups</a>
                </li>
                <li>
                    <a href="@Url.RouteUrl(PayrollUtilsControllerRoute.GetAllRenumSchemes)">Renum. Schemes</a>
                </li>
            </ul>
        </li>
    </ul>
</li>

com.nita/Views/Shared/_PrintHeader.cshtml
@inject IOptionsSnapshot<AppSettings> AppSettings
@*
    For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860
*@

<div class="text-center">
    <img src="~/img/nita-logo.jpg" height="48" />
    <p class="text-center font-bold" style="font-size:20px"><b>@AppSettings.Value.SiteTitle.ToUpper()</b> <span></span></p>
    <p class="text-center font-bold" style="font-size:12px">@Html.Raw(AppSettings.Value.Address)</p>
</div>

com.nita/Views/Shared/_TempLayout.cshtml
@RenderBody()

@RenderSection("scripts", required: false)